name: Build Godot Project

on:
  pull_request:
    branches:
      - dev

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - preset: Windows Desktop
            name: Windows-exe
            extention: ".exe"
          - preset: Windows Dedicated
            name: Windows-Dedicated-exe
            extention: ".exe"
          - preset: Linux/X11
            name: Linux-x86
            extention: ".x86_64"
          - preset: Linux Docker
            name: Linux-Dedicated-x86
            extention: ".x86_64"
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: lillian1024/godot-mono-action@v1.0
        with:
          name: Atria${{ matrix.platform.extention }}
          preset: ${{ matrix.platform.preset }}
          debugMode: "true"
