name: Build Godot Project

on:
  push:
    branches:
      - dev
    tags:
      - 'build-**'
  pull_request:
    branches:
      - dev
      - main

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - name: Windows Desktop
          - name: Linux-X11
          - name: Linux/X11
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: Atria
          preset: ${{ matrix.platform.name }}
          debugMode: "true"
