name: Build Godot Project

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - name: Windows
            file: game.exe
          - name: MacOS
            file: game.zip
          - name: Linux
            file: game.zip
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: ${{ matrix.platform.file }}
          preset: ${{ matrix.platform.name }}
          debugMode: "true"
