name: Build Godot Project

on:
  push:
    branches:
      - dev
    tags:
      - 'build-**'
  pull_request:
    branches:
      - dev
      - main

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - preset: Windows Desktop
            name: Windows-exe
          - preset: Linux/X11
            name: Linux-x86
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: lillian1024/godot-mono-action@v0.1
        with:
          name: Atria
          preset: ${{ matrix.platform.preset }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Client - ${{ matrix.platform.name }}
          path: ./build/
